Repository Shubhashish-Chakraborty/prepnerdz, pull requests merged in 2025-08, with the labels that each got.

#63 Feat: Add Confirm Password input field to the Signup Page
  apps/web/components/modals/Signup.tsx
Labels: gssoc25, Level 1

#72 fix: resolve uneven box heights on Features section
  apps/web/components/ui/cards/FloatingSimple.tsx
Labels: gssoc25, Level 1

#65 Seo Improved
  apps/web/app/about/layout.tsx
  apps/web/app/about/page.tsx
  apps/web/app/contact-us/layout.tsx
  apps/web/app/contact-us/page.tsx
  apps/web/app/contributors/page.tsx
  apps/web/app/dashboard/page.tsx
  apps/web/app/forgot-password/page.tsx
  apps/web/app/leaderboard/page.tsx
  apps/web/app/mybookmarks/page.tsx
  apps/web/app/privacy-policy/page.tsx
  apps/web/app/sitemap.xml/route.ts
  apps/web/app/terms-and-conditions/page.tsx
  apps/web/app/testimonials/page.tsx
  apps/web/public/sitemap-0.xml
  apps/web/public/sitemap.xml
Labels: gssoc25, Level 3

#79 Adjust Spacing Between “Send Message” #78
  apps/web/components/pages/Contact.tsx
Labels: gssoc25, Level 1

#90 Updated AskNerds Chatbot Context
  apps/web/app/api/chat/context.ts
Labels: gssoc25, Level 2

#101 Feature : Combined and merged Dashboard Avatar icon and Three Dot menu
  apps/web/components/ui/DashboardHeader.tsx
  apps/web/icons/Settings.tsx
Labels: gssoc25, Level 1

#102 Fix: Resolved Header Overlap Issue on Leaderboard Page
  apps/web/app/leaderboard/page.tsx
  apps/web/components/ui/DashboardHeader.tsx
  apps/web/components/ui/navbars/Leaderboard-Navbar.tsx
Labels: gssoc25, Level 1

#115 feat: Implement custom cursor animation
  apps/web/app/layout.tsx
  apps/web/components/FluidCursor.tsx
  apps/web/hooks/use-FluidCursor.tsx
  apps/web/package.json
  package-lock.json
Labels: gssoc25, Level 2

#110 Added Cursor Effect
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/components/Mouse/CursorEffect.tsx
Labels: gssoc25, Level 2

#124 fix: Chatbot Icon #123
  apps/web/components/ui/AskNerd.tsx
Labels: gssoc25, Level 1

#126 feat/added-tooltip-for-navbar-dropdown
  apps/web/app/globals.css
  apps/web/components/ui/navbars/Navbar.tsx
Labels: gssoc25, Level 1
